switch to use mutex in AbstractHandle.wait method
karafka/rdkafka-ruby pull request #417
Opened 2024-03-01 17:41 UTC by nijikon

Closes https://github.com/karafka/rdkafka-ruby/issues/390

2024-03-04 14:26 UTC, mensfeld requested changes

2024-03-04 14:26 UTC, mensfeld commented on lib/rdkafka/abstract_handle.rb
> +    #   If this is nil we will use WAIT_TIMEOUT value
"If this is nil, will wait forever" would be more explicit IMHO. WAIT_TIMEOUT is an implementation detail

2024-03-04 14:26 UTC, mensfeld commented on lib/rdkafka/callbacks.rb
> +          create_topic_handle.broadcast
can we name it "unlock" or something similar? broadcast seems outside of our domain

2024-03-06 14:50 UTC, mensfeld approved these changes

2024-03-09 09:32 UTC, nijikon commented
@thijsc will you have time this coming week to look at this change?

2024-03-11 08:45 UTC, thijsc approved these changes
This looks good to me.

2024-03-11 14:13 UTC, merged